language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
services:
- mongodb
- redis
env:
  global:
  - REDIS_HOST=localhost
  - REDIS_PORT=6379
  matrix:
  - USE_MONGO=true
  - USE_MONGO=false
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: "PWUGkix9QPeOVdeEKwXM1DioZsxOD7YXLjcMNm4yghyDwWtkPIn5b98Fay5A8CfiUjngjviUb63X2KhqYE/kglWETp7BsbSzOhgDqv8qbnsK4MVtzk30fphX+FcVo9RSd37G6S3cT58DnJ9CtK6Z+Hp/44U59w2AXdoRr3i8/Ys="
  app-id: e1883763-9db4-432f-900a-628dd84aceaa
  on:
    branch: production
    condition: $USE_MONGO = true
- provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  app-id: 7b21bb86-93bb-4a2b-b482-7a8a3ab4a23b
  on:
    branch: production
    condition: $USE_MONGO = true
- provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  app-id: c9b4255f-bc9e-4368-a998-a26ea9ac4f7f
  on:
    branch: production
    condition: $USE_MONGO = true
- provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  app-id: 5fcc76e4-b0cc-41d3-b794-8a8b4ff0ed9e
  on:
    branch: staging
    condition: $USE_MONGO = true
- provider: opsworks
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  app-id: 3110aaa3-dd25-49d1-be43-6c0ac5c0a8ad
  on:
    branch: staging
    condition: $USE_MONGO = true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "VZ8QsaPZEWhRaEQM7Az6p8UcKzG2Ew7BF4tuZe2pD56zeV0orr9Fn8i9wz4NAc1DB0fW0LaKAw3qCWOJ0gK6uL0zzRE4+faQERIsRKef6XqOteKbvb9oNffWMBCR1N4FNEK2LVIkmzkMcAPIhHHkmvWxjjZVuMGY5PJ+Oo1ZUw0="
  on:
    tags: true
    branches: true
addons:
  code_climate:
    repo_token: 8e3f39fe338fe8465f0400555fcbf8a2a3293f9c586b64588e8ce198e64bda58
before_install:
- npm install -g npm
before_script:
- npm install -g codeclimate-test-reporter meshblu-util
script:
- npm test
after_script:
- codeclimate-test-reporter < coverage/lcov.info
